apiVersion: entity.humanitec.io/v1b1
kind: Definition
metadata:
  id: custom-namespace
entity:
  name: custom-namespace
  type: k8s-namespace
  driver_type: humanitec/template
  driver_inputs:
    values:
      templates:
        init: |
          name: ${context.env.id}-${context.app.id}
        manifests:
          - location: cluster
            data:
              apiVersion: v1
              kind: Namespace
              metadata:
                name: {{ .init.name | default "undefined" }}
                labels:
                  environment: dev
                annotations:
                  managed-by: humanitec
        outputs: |
          namespace: {{ .init.name }}
criteria:
  - {}
