name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r src/requirements.txt

          - name: Install humctl
          run: |
            echo "Baixando humctl..."
            curl -L -o humctl-linux-amd64 -w "%{http_code}" https://github.com/humanitec/cli/releases/latest/download/humctl-linux-amd64
            # Verifica se o download foi bem sucedido (código HTTP 200)
            if [ "$(file humctl-linux-amd64 | grep 'ELF')" ]; then
              echo "Download bem-sucedido."
              chmod +x humctl-linux-amd64
              sudo mv humctl-linux-amd64 /usr/local/bin/humctl
              humctl --version
            else
              echo "Falha ao baixar o humctl. Verifique a URL."
              cat humctl-linux-amd64
              exit 1
            fi

      - name: Login to Humanitec
        env:
          HUMANITEC_TOKEN: ${{ secrets.HUMANITEC_API_TOKEN }}
        run: |
          echo "Logging into Humanitec..."
          humctl login --token "$HUMANITEC_TOKEN"

      - name: Validate Score file
        run: humctl score validate

      - name: Deploy using Humanitec
        run: humctl score deploy --wait
