name: Deploy to Humanitec

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t myapp:${{ github.sha }} .

      - name: Push Docker image to ACR
        env:
          ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
          ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
          ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
        run: |
          docker login ${{ env.ACR_LOGIN_SERVER }} -u ${{ env.ACR_USERNAME }} -p ${{ env.ACR_PASSWORD }}
          docker tag myapp:${{ github.sha }} ${{ env.ACR_LOGIN_SERVER }}/myapp:${{ github.sha }}
          docker push ${{ env.ACR_LOGIN_SERVER }}/myapp:${{ github.sha }}

  trigger-humanitec:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Trigger Humanitec Pipeline
        env:
          HUMANITEC_API_TOKEN: ${{ secrets.HUMANITEC_API_TOKEN }}
        run: |
          curl -X POST https://api.humanitec.io/orgs/labcle/apps/humanitec-poc/envs/dev/deploys \
          -H "Authorization: Bearer ${{ secrets.HUMANITEC_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "modules": {
              "myapp": {
                "image": "'"${{ secrets.ACR_LOGIN_SERVER }}/myapp:${{ github.sha }}"'"
              }
            }
          }'
