name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r src/requirements.txt

      - name: Install humctl
        run: |
          curl -LO https://github.com/humanitec/cli/releases/latest/download/humctl-linux-amd64
          sudo install humctl-linux-amd64 /usr/local/bin/humctl

      - name: Login to Humanitec
        run: humctl login --token ${{ secrets.HUMANITEC_API_TOKEN }}

      - name: Validate Score file
        run: humctl score validate

      - name: Deploy using Humanitec
        run: humctl score deploy --wait
